package view;

/**
 *
 * @author julia
 */

import java.awt.BorderLayout;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class RooMaking extends javax.swing.JFrame {
    
    private JFXPanel fxPanel;

    public RooMaking() {
        
        initComponents();
        initFXPanel();
    }
    
private void initFXPanel() {
    try {
        fxPanel = new JFXPanel();
        javaFXPanel.setLayout(new BorderLayout());
        javaFXPanel.add(fxPanel, BorderLayout.CENTER);
        getContentPane().setBackground(new java.awt.Color(168,209,165)); // SkyBlue
        Platform.runLater(() -> {
            RooMakingJFX3D rooMakingJFX = new RooMakingJFX3D();
            rooMakingJFX.start(new Stage()); // Inicializa RoomDesigner3D
            Scene scene = rooMakingJFX.getSubScene().getRoot().getScene(); // Obtiene la escena de RoomDesigner3D
            fxPanel.setScene(scene);
        });
    } catch (Exception e) {
        e.printStackTrace();
        // Maneja la excepción apropiadamente, por ejemplo, mostrando un mensaje de error al usuario
    }
}    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVolver = new javax.swing.JButton();
        javaFXPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javaFXPanel.setForeground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout javaFXPanelLayout = new javax.swing.GroupLayout(javaFXPanel);
        javaFXPanel.setLayout(javaFXPanelLayout);
        javaFXPanelLayout.setHorizontalGroup(
            javaFXPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        javaFXPanelLayout.setVerticalGroup(
            javaFXPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(botonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(javaFXPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(514, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(javaFXPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVolver)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel javaFXPanel;
    // End of variables declaration//GEN-END:variables
}
