package viewConfiguracion;

import controller.services.ServicesUsuario;
import java.awt.Color;
import view.Menu;

/**
 *
 * @author julia
 */
public class ConfiguracionView extends javax.swing.JFrame {

    public ConfiguracionView() {
        initComponents();
        grupoBotones.add(botonNo);
        grupoBotones.add(botonSi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonSi = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TextContraActualContra = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        TextActualizaNuevaContra = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        TextActualizaConfirmContra = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        BtActualizaConstraseña = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        TextActualizaUsuario2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        TextActualizaUsuario1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TextActualizaUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtActualizaUsuario = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        TextConfirmContrActual = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        TextContraActual3 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        TextNuevoCorreoo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        TextNuevoNombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BtActualizPerfil = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        botonNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(162, 217, 206));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/data_management_data_processing_setting_configuration_gear_icon_190642.png"))); // NOI18N
        jLabel1.setText("Configuración");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Roboto Black", 2, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewLogearseRegistrarse/logochiquito.png"))); // NOI18N
        jLabel9.setText("RooMade");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        jPanel3.setBackground(new java.awt.Color(245, 245, 220));

        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(botonSi)
                .addGap(157, 157, 157))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(botonSi))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 70));

        jPanel6.setBackground(new java.awt.Color(248, 248, 233));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel7.setText("Cambiar Contraseña:");

        TextContraActualContra.setBackground(new java.awt.Color(248, 248, 233));
        TextContraActualContra.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextContraActualContra.setForeground(new java.awt.Color(204, 204, 204));
        TextContraActualContra.setText("Contraseña Actual");
        TextContraActualContra.setBorder(null);
        TextContraActualContra.setCaretColor(new java.awt.Color(204, 204, 204));
        TextContraActualContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextContraActualContraMousePressed(evt);
            }
        });
        TextContraActualContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextContraActualContraActionPerformed(evt);
            }
        });

        TextActualizaNuevaContra.setBackground(new java.awt.Color(248, 248, 233));
        TextActualizaNuevaContra.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaNuevaContra.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaNuevaContra.setText("Nueva Contraseña");
        TextActualizaNuevaContra.setBorder(null);
        TextActualizaNuevaContra.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaNuevaContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaNuevaContraMousePressed(evt);
            }
        });
        TextActualizaNuevaContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaNuevaContraActionPerformed(evt);
            }
        });

        TextActualizaConfirmContra.setBackground(new java.awt.Color(248, 248, 233));
        TextActualizaConfirmContra.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaConfirmContra.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaConfirmContra.setText("Confirmar Contraseña");
        TextActualizaConfirmContra.setBorder(null);
        TextActualizaConfirmContra.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaConfirmContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaConfirmContraMousePressed(evt);
            }
        });
        TextActualizaConfirmContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaConfirmContraActionPerformed(evt);
            }
        });

        BtActualizaConstraseña.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BtActualizaConstraseña.setForeground(new java.awt.Color(153, 153, 153));
        BtActualizaConstraseña.setText("Actualizar Contraseña");
        BtActualizaConstraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtActualizaConstraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextContraActualContra, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(TextActualizaNuevaContra, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(TextActualizaConfirmContra, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BtActualizaConstraseña)))
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextContraActualContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextActualizaNuevaContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextActualizaConfirmContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(BtActualizaConstraseña)
                .addGap(44, 44, 44))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 280, 310));

        jPanel7.setBackground(new java.awt.Color(255, 255, 250));

        TextActualizaUsuario2.setBackground(new java.awt.Color(255, 255, 250));
        TextActualizaUsuario2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario2.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario2.setText("Confirmar Contraseña");
        TextActualizaUsuario2.setBorder(null);
        TextActualizaUsuario2.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario2MousePressed(evt);
            }
        });
        TextActualizaUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario2ActionPerformed(evt);
            }
        });

        TextActualizaUsuario1.setBackground(new java.awt.Color(255, 255, 250));
        TextActualizaUsuario1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario1.setText("Contraseña Actual");
        TextActualizaUsuario1.setBorder(null);
        TextActualizaUsuario1.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario1MousePressed(evt);
            }
        });
        TextActualizaUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario1ActionPerformed(evt);
            }
        });

        TextActualizaUsuario.setBackground(new java.awt.Color(255, 255, 250));
        TextActualizaUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario.setText("Nuevo Usuario");
        TextActualizaUsuario.setBorder(null);
        TextActualizaUsuario.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuarioMousePressed(evt);
            }
        });
        TextActualizaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel6.setText("Actualizar Usuario:");

        BtActualizaUsuario.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BtActualizaUsuario.setForeground(new java.awt.Color(153, 153, 153));
        BtActualizaUsuario.setText("Actualizar Usuario");
        BtActualizaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtActualizaUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextActualizaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextActualizaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextActualizaUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BtActualizaUsuario)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(14, 14, 14)
                .addComponent(TextActualizaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextActualizaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(TextActualizaUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(BtActualizaUsuario)
                .addGap(45, 45, 45))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 310));

        jPanel8.setBackground(new java.awt.Color(255, 255, 250));

        TextConfirmContrActual.setBackground(new java.awt.Color(255, 255, 250));
        TextConfirmContrActual.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextConfirmContrActual.setForeground(new java.awt.Color(204, 204, 204));
        TextConfirmContrActual.setText("Confirmar Contraseña");
        TextConfirmContrActual.setBorder(null);
        TextConfirmContrActual.setCaretColor(new java.awt.Color(204, 204, 204));
        TextConfirmContrActual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextConfirmContrActualMousePressed(evt);
            }
        });
        TextConfirmContrActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextConfirmContrActualActionPerformed(evt);
            }
        });

        TextContraActual3.setBackground(new java.awt.Color(255, 255, 250));
        TextContraActual3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextContraActual3.setForeground(new java.awt.Color(204, 204, 204));
        TextContraActual3.setText("Contraseña Actual");
        TextContraActual3.setBorder(null);
        TextContraActual3.setCaretColor(new java.awt.Color(204, 204, 204));
        TextContraActual3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextContraActual3MousePressed(evt);
            }
        });
        TextContraActual3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextContraActual3ActionPerformed(evt);
            }
        });

        TextNuevoCorreoo.setBackground(new java.awt.Color(255, 255, 250));
        TextNuevoCorreoo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextNuevoCorreoo.setForeground(new java.awt.Color(204, 204, 204));
        TextNuevoCorreoo.setText("Nuevo Correo");
        TextNuevoCorreoo.setBorder(null);
        TextNuevoCorreoo.setCaretColor(new java.awt.Color(204, 204, 204));
        TextNuevoCorreoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextNuevoCorreooMousePressed(evt);
            }
        });
        TextNuevoCorreoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNuevoCorreooActionPerformed(evt);
            }
        });

        TextNuevoNombres.setBackground(new java.awt.Color(255, 255, 250));
        TextNuevoNombres.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextNuevoNombres.setForeground(new java.awt.Color(204, 204, 204));
        TextNuevoNombres.setText("Nuevo Nombre");
        TextNuevoNombres.setBorder(null);
        TextNuevoNombres.setCaretColor(new java.awt.Color(204, 204, 204));
        TextNuevoNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextNuevoNombresMousePressed(evt);
            }
        });
        TextNuevoNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNuevoNombresActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setText("Actualizar Perfil:");

        BtActualizPerfil.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BtActualizPerfil.setForeground(new java.awt.Color(153, 153, 153));
        BtActualizPerfil.setText("Actualizar Perfil");
        BtActualizPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtActualizPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(TextNuevoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNuevoCorreoo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextContraActual3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextConfirmContrActual, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(BtActualizPerfil)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextNuevoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TextNuevoCorreoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextContraActual3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextConfirmContrActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BtActualizPerfil)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 260, 310));

        jPanel5.setBackground(new java.awt.Color(168, 209, 165));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar Datos: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jPanel4.setBackground(new java.awt.Color(168, 209, 165));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Modo oscuro: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 50));

        jPanel9.setBackground(new java.awt.Color(245, 245, 220));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(botonNo)
                .addGap(93, 93, 93)
                .addComponent(jLabel4)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonNo)
                    .addComponent(jLabel4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 410, 70));

        jPanel10.setBackground(new java.awt.Color(245, 245, 220));

        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(104, 104, 104));
        jButton1.setText("Volver...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addContainerGap(716, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 810, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSiActionPerformed

    private void BtActualizaConstraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtActualizaConstraseñaActionPerformed
        ServicesUsuario servUsuario = new ServicesUsuario();
        if(TextActualizaNuevaContra.getText().equals(TextActualizaConfirmContra.getText())){
            servUsuario.actualizar_password(TextActualizaNuevaContra.getText(), ServicesUsuario.getUsuario());
            javax.swing.JOptionPane.showMessageDialog(this, "Los datos se guardaron correctamente. ");
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
        }
    }//GEN-LAST:event_BtActualizaConstraseñaActionPerformed

    private void TextActualizaUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuarioMousePressed
        if(TextActualizaUsuario.getText().equals("Nuevo Usuario")){
            TextActualizaUsuario.setText("");
            TextActualizaUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextActualizaUsuarioMousePressed

    private void TextActualizaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuarioActionPerformed
        
    }//GEN-LAST:event_TextActualizaUsuarioActionPerformed

    private void TextActualizaUsuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario1MousePressed
        if(TextActualizaUsuario1.getText().equals("Contraseña Actual")){
            TextActualizaUsuario1.setText("");
            TextActualizaUsuario1.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextActualizaUsuario1MousePressed

    private void TextActualizaUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario1ActionPerformed
       
    }//GEN-LAST:event_TextActualizaUsuario1ActionPerformed

    private void TextActualizaUsuario2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario2MousePressed
        if(TextActualizaUsuario2.getText().equals("Confirmar Contraseña")){
            TextActualizaUsuario2.setText("");
            TextActualizaUsuario2.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextActualizaUsuario2MousePressed

    private void TextActualizaUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario2ActionPerformed
        
    }//GEN-LAST:event_TextActualizaUsuario2ActionPerformed

    private void TextContraActualContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextContraActualContraMousePressed
        if(TextContraActualContra.getText().equals("Contraseña Actual")){
            TextContraActualContra.setText("");
            TextContraActualContra.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextContraActualContraMousePressed

    private void TextContraActualContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextContraActualContraActionPerformed
        
    }//GEN-LAST:event_TextContraActualContraActionPerformed

    private void TextActualizaNuevaContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaNuevaContraMousePressed
        if(TextActualizaNuevaContra.getText().equals("Nueva Contraseña")){
            TextActualizaNuevaContra.setText("");
            TextActualizaNuevaContra.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextActualizaNuevaContraMousePressed

    private void TextActualizaNuevaContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaNuevaContraActionPerformed
        
    }//GEN-LAST:event_TextActualizaNuevaContraActionPerformed

    private void TextActualizaConfirmContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaConfirmContraMousePressed
        if(TextActualizaConfirmContra.getText().equals("Confirmar Contraseña")){
            TextActualizaConfirmContra.setText("");
            TextActualizaConfirmContra.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextActualizaConfirmContraMousePressed

    private void TextActualizaConfirmContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaConfirmContraActionPerformed
        
    }//GEN-LAST:event_TextActualizaConfirmContraActionPerformed

    private void TextNuevoCorreooMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextNuevoCorreooMousePressed
        if(TextNuevoCorreoo.getText().equals("Nuevo Correo")){
            TextNuevoCorreoo.setText("");
            TextNuevoCorreoo.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextNuevoCorreooMousePressed

    private void TextNuevoCorreooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNuevoCorreooActionPerformed
        
    }//GEN-LAST:event_TextNuevoCorreooActionPerformed

    private void TextContraActual3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextContraActual3MousePressed
        if(TextContraActual3.getText().equals("Contraseña Actual")){
            TextContraActual3.setText("");
            TextContraActual3.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextContraActual3MousePressed

    private void TextContraActual3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextContraActual3ActionPerformed
        
    }//GEN-LAST:event_TextContraActual3ActionPerformed

    private void TextConfirmContrActualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextConfirmContrActualMousePressed
        if(TextConfirmContrActual.getText().equals("Confirmar Contraseña")){
            TextConfirmContrActual.setText("");
            TextConfirmContrActual.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextConfirmContrActualMousePressed

    private void TextConfirmContrActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextConfirmContrActualActionPerformed
        
    }//GEN-LAST:event_TextConfirmContrActualActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextNuevoNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNuevoNombresActionPerformed
        
    }//GEN-LAST:event_TextNuevoNombresActionPerformed

    private void TextNuevoNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextNuevoNombresMousePressed
        if(TextNuevoNombres.getText().equals("Nuevo Nombre")){
            TextNuevoNombres.setText("");
            TextNuevoNombres.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextNuevoNombresMousePressed

    private void BtActualizaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtActualizaUsuarioActionPerformed
        ServicesUsuario servUsuario = new ServicesUsuario();
        if(TextActualizaUsuario1.getText().equals(TextActualizaUsuario2.getText())){
            servUsuario.actualizar_usuario(TextActualizaUsuario.getText(), ServicesUsuario.getUsuario());
            javax.swing.JOptionPane.showMessageDialog(this, "Los datos se guardaron correctamente. ");
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
        }
    }//GEN-LAST:event_BtActualizaUsuarioActionPerformed

    private void BtActualizPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtActualizPerfilActionPerformed
        ServicesUsuario servUsuario = new ServicesUsuario();
        if(TextContraActual3.getText().equals(TextConfirmContrActual.getText())){
            servUsuario.actualizar_nombres(TextNuevoNombres.getText(), ServicesUsuario.getUsuario());
            servUsuario.actualizar_email(TextNuevoCorreoo.getText(), ServicesUsuario.getUsuario());
            javax.swing.JOptionPane.showMessageDialog(this, "Los datos se guardaron correctamente. ");
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
        }
    }//GEN-LAST:event_BtActualizPerfilActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtActualizPerfil;
    private javax.swing.JButton BtActualizaConstraseña;
    private javax.swing.JButton BtActualizaUsuario;
    private javax.swing.JTextField TextActualizaConfirmContra;
    private javax.swing.JTextField TextActualizaNuevaContra;
    private javax.swing.JTextField TextActualizaUsuario;
    private javax.swing.JTextField TextActualizaUsuario1;
    private javax.swing.JTextField TextActualizaUsuario2;
    private javax.swing.JTextField TextConfirmContrActual;
    private javax.swing.JTextField TextContraActual3;
    private javax.swing.JTextField TextContraActualContra;
    private javax.swing.JTextField TextNuevoCorreoo;
    private javax.swing.JTextField TextNuevoNombres;
    private javax.swing.JRadioButton botonNo;
    private javax.swing.JRadioButton botonSi;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
